#!/bin/sh
# Run the expire function of  non-interactively (unless errors 
# are detected).

# optional, specify hostname to appear in error messages and links
# HOSTNAME=externallyVisibleHostName
# export HOSTNAME

test -x /usr/lib//acngtool || exit 0
/usr/lib//acngtool maint -c /etc/ SocketPath=/var/run//socket
