Document: i2p-apt-cacher-ng
Title: Debian i2p-apt-cacher-ng Manual
Author: <insert document author here>
Abstract: This manual describes what i2p-apt-cacher-ng is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/i2p-apt-cacher-ng/i2p-apt-cacher-ng.sgml.gz

Format: postscript
Files: /usr/share/doc/i2p-apt-cacher-ng/i2p-apt-cacher-ng.ps.gz

Format: text
Files: /usr/share/doc/i2p-apt-cacher-ng/i2p-apt-cacher-ng.text.gz

Format: HTML
Index: /usr/share/doc/i2p-apt-cacher-ng/html/index.html
Files: /usr/share/doc/i2p-apt-cacher-ng/html/*.html
